---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Add docker repo
    template: src=docker.repo.j2 dest=/etc/yum.repos.d/docker.repo
  - name: Install Docker
    yum: name=docker-ce state=latest
  - name: Starting docker 
    service: name=docker state=started enabled=yes
  - name: Install epel-release
    yum: name=epel-release state=latest
  - name: Installing dependencies
    yum: name=python-pip state=latest
  - name: Installing docker compose
    pip:
      name: docker-compose
      state: present  
  - name: Create /etc/nginx
    command: mkdir /etc/nginx
  - name: Configure Nginx
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  - name: Transfer over docker-compose.yml
    template: src=docker-compose-nginx.yml.j2 dest=/usr/local/src/docker-compose.yml
  - name: Start containers from docker-compose file
    shell: docker-compose up -d
    args:
      chdir: /usr/local/src
  - name: Add certificates
    template: src=comprigo-tzidanic.tk.crt.j2 dest=/etc/ssl/comprigo-tzidanic.crt
  - name: Upload key
    template: src=comprigo-tzidanic.tk.key.j2 dest=/etc/ssl/comprigo-tzidanic.key
  - name: Configure php.ini
    template: src=php.ini.j2 dest=/etc/php.ini
  - name: Create php-fpm dir
    shell: mkdir /etc/php-fpm.d/
  - name: Configure php-fpm
    template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  - name: Place hello world index.php
    template: src=index.php.j2 dest=/usr/share/nginx/html/index.php
  - name: Start Nginx
    shell: docker restart nginx
    args:
      executable: /bin/bash
  - name: Configure Redis
    template: src=redis.conf.j2 dest=/etc/redis.conf
  - name: Make sure Redis is started
    shell: docker restart redis
    args:
      executable: /bin/bash
  - name: Insert Timer Unit file bash script
    template: src=redis-script.sh.j2 dest=/usr/share/redis-script.sh mode=0755
  - name: Set cron to execute the script
    cron: minute=5 name=Load_dummy_data_into_redis cron_file=redis-script.sh user=root job=/usr/share/redis-script.sh
  - name: Restart Nginx
    shell: docker restart nginx
    args:
      executable: /bin/bash
